In [23]:
# LabelEncoder import
from sklearn.preprocessing import LabelEncoder
import numpy as np

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

# Encoding 모형을 Label Encoding으로 설정
encoder = LabelEncoder()

# 학습 및 변환
labels = encoder.fit_transform(items)

print(labels)

[0 1 4 5 3 2 2]


In [25]:
# 변환된 숫자(코드)에 대응되는 범주형 변수값 출력하기
print(encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [26]:
# 숫자(코드)를 범주형 변수로 역변환
print(encoder.inverse_transform([0,1,4,5,3,2,2]))

['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '믹서' '믹서']


In [27]:
# OneHotEncoder import
from sklearn.preprocessing import OneHotEncoder

# One-hot encoding을 준비하기 위해 열이 하나인 2차원 배열로 구조 변환
labels = labels.reshape(-1, 1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [2],
       [2]], dtype=int64)

In [28]:
# Encoding 모형을 One-hot encoding으로 설정
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print(oh_labels)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 2)	1.0
  (6, 2)	1.0


In [29]:
# Encoding 결과를 2차원 배열로 변환
print(oh_labels.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
